# Generated by Django 5.0.7 on 2024-07-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'Aplus'), ('A-', 'Aless'), ('B+', 'Bplus'), ('B-', 'Bless'), ('AB', 'Abplus'), ('AB-', 'Abless'), ('O+', 'Oplus'), ('O-', 'Oless')], max_length=3),
        ),
    ]
