# Generated by Django 5.0.7 on 2024-07-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donor_identification_alter_donor_blood_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='identification',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
