# Generated by Django 5.0.7 on 2024-07-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_alter_donor_identification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='name',
            new_name='donor',
        ),
    ]
