# Generated by Django 5.0.7 on 2024-07-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_alter_donation_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='next_donation',
            field=models.DateTimeField(null=True),
        ),
    ]
